lang: zh-CN
title: Coderd's Blog 
tagline: 记录猿生活
description: >-                        
  coderd的博客，记录猿生活，主要从事 iOS 开发。
github:
  username: FaJieDeng
social:
  name: coderd
  email: 3056425582@qq.com            
  links:
    - https://github.com/FaJieDeng 
   
img_cdn:
# avatar: '/assets/img/avatar.jpeg'
   
# 百度统计,自己添加，后面扩展百度统计会用到
# baidu_tongji: 2719c746097363a5ec9ba07dce73754d

